### ISSUE TITLE
Add environment (browser) checks

### ISSUE THREAD

**Issue by blockkeeper** [blockkeeper/blockkeeper-frontend-web#1]
At startup, check if user has a modern browser environment, block old browsers.

**Comment by yeahoffline** [comment]
could integrate something like:

https://github.com/kni-labs/old-browsers
https://github.com/burocratik/outdated-browser

but i guess our users are mostly mobile or on modern browsers?

**Comment by d3ck-org** [comment]
They should be :) Cause of our very modern setup and security reasons, I think it makes sense to really **block** old browsers.
