### ISSUE TITLE
Error handling invalid blockexplorer address

### ISSUE THREAD

**Issue by yeahoffline** [blockkeeper/blockkeeper-frontend-web#17]
https://github.com/blockkeeper/blockkeeper-frontend-web/blob/master/src/logic/coin/Lib.js#L75

since the requests are batched it is not possible to monitor single address errors. 

replicate error: add a invalid (btc) address. 
pld will be:  ```{error: "Address asdfasdfasfafasdfasfdasfasfasfas is invalid: Address asdfasdfasfafasdfasfdasfasfasfas is of unknown size."}```

**Comment by d3ck-org** [comment]
Forcing valid addresses makes this problem obsolet: In depth address validation should be occur when the user creates the address.

I will rework the validation in the course of xpub-key integration.
