### ISSUE TITLE
User locale selector 

### ISSUE THREAD

**Issue by yeahoffline** [blockkeeper/blockkeeper-frontend-web#19]

**Comment by d3ck-org** [comment]
Numbers need locale formatting.

The underlying setting will be stored in user preferences and is accessible after loading the user data: `user = this.cx.user.load() -> user.locale`.

Please note: In depot/addr/tsc view the user data loading is already implementend (71707ca765369b1f073c689439b42d0ab9f30795) and the locale is accessible via `this.user.locale`.
