### ISSUE TITLE
Transaction fees are missing

### ISSUE THREAD

**Issue by yeahoffline** [blockkeeper/blockkeeper-frontend-web#21]

**Comment by d3ck-org** [comment]
Not a bug, it's a feature: The current blockexplorer call doesn't return the fee. A lot of extra calls would be needed to get these informations. In my opinion the fee is not important enough to make such huge efforts - Has to be discussed.

**Comment by yeahoffline** [comment]
Yes. Right now the different values between our addr/tsc overview and those external block explorers confuse me (and maybe others)

**Comment by d3ck-org** [comment]
As discussed: The problem of different views/description in various blockexplorers/applications is present: (In the first version) We need to accept it :)
