### ISSUE TITLE
Index screen should reload rates and user data

### ISSUE THREAD

**Issue by yeahoffline** [blockkeeper/blockkeeper-frontend-web#22]

**Comment by d3ck-org** [comment]
Why the user data?

Reloading the rates is (like address/transaction updates) a synchronization process which per definition should be initiated by the user.
So: Perhaps it's better to always reload the rates when an address/transaction synchronization process occurs?

**Comment by d3ck-org** [comment]
Now, rates will be loaded at startup/login and before synchronizing addresses/transactions.
Reloading user data: See #24.
