### ISSUE TITLE
Encrypt/Decrypt payloads with Web-Cryptography-API

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-frontend-web#25]
All API related classes like `Addr`contain the `this.encrypt -> this.cx.core.encrypt` + `this.decrypt() -> this.cx.core.decrypt` functions. This functions are methods of the `logic/Core` module:

```
$ cat logic/Core.js
...
  toSecret (username, pw) { 
    ...
  }

  encrypt (pld, secret, noFatal) {
    ...
  }

  decrypt (pld, secret, noFatal) {
    ...
  }
...
```

`Core`'s `encrypt()`, `decrypt()` and the related `toSecret()` need to be implemented. The underlying standard for the implementation is the [Web Cryptography API](https://www.w3.org/TR/WebCryptoAPI/):

- [MDN: Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)
- [Web Cryptography API Examples](https://github.com/diafygi/webcrypto-examples)
- [Webkit Web Cryptography](https://webkit.org/blog/7790/update-on-web-cryptography/)
- [A closer look at the Web Cryptography API](https://golb.hplar.ch/p/A-closer-look-at-the-Web-Cryptography-API) (2017-09-25)
    - _With the release of Safari 11 we finally get a complete Web Cryptography implementation in Apple's browser. All major browsers now support Web Cryptography._

**Comment by yeahoffline** [comment]
bbb3507f2c8230056527a1a5409490c23ab01c86
