### ISSUE TITLE
Address-/Transaction edit-button should be disabled when user enters invalid data

### ISSUE THREAD

**Issue by d3ck-org** [blockkeeper/blockkeeper-frontend-web#30]
Address/Transaction detail view:

Currently, invalid data entered by user is ignored (and not stored). Hence and because passing the validation-state to Lib's _TopBar_ component is somewhat difficult, marking issue only as _enhancement_.

**Comment by yeahoffline** [comment]
abf81bb6440e602439d416d80664ba68859faf9b
