### ISSUE TITLE
Web login/registr keeps loading

### ISSUE THREAD

**Issue by unto01** [blockkeeper/blockkeeper-frontend-web#43]
After installing and after clicking register.. it loads and loads under firefox, the page does not finish registration, neither does it login with details i tried registering with.

Please can you help?

I am using Ubuntu 18.04 and Firefox latest version (clean, no addons)

**Comment by DanielSanW** [comment]
Sorry, I can't reproduce the issue under Ubuntu 18.04 with latest Firefox version. It works perfectly on my side with login and signup. Have you tried chromium?

**Comment by unto01** [comment]
i tried on a different PC.
and i get the following (issues) when installing with yarn
```
$blockkeeper-frontend-web$ yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @material-ui/icons@1.0.0" has incorrect peer dependency "@material-ui/core@^1.0.0-rc.0".
warning " > qrcode-react@0.1.16" has incorrect peer dependency "react@0.12 - 16.2".
warning " > react-transitive-number@3.1.0" has incorrect peer dependency "react@^15.0.0".
warning " > react-transitive-number@3.1.0" has incorrect peer dependency "react-dom@^15.0.0".
[4/4] Building fresh packages...
Done in 107.64s.
```

**Comment by yeahoffline** [comment]
yarn looks good.

if you develop locally you need to mock the backend or disable cors in your browser.

**Comment by unto01** [comment]
@yeahoffline im sorry but ive literally tried every possible thing i can think of. This issue persists.
Unless im missing a critical command or component in the system then im out of options and ive wasted a LOT of time on getting this to work.

This is what i did on a fresh VM:
```
sudo apt-get install curl software-properties-common
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn
curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
sudo apt-get install nodejs
git clone https://github.com/blockkeeper/blockkeeper-frontend-web
cd blockkeeper-frontend-web/
yarn install
yarn start
```

After this, it opens up, in Firefox (AND ive also tried CHROME, but same issue happens) it keeps loading forever.
See the video i made
![2019-05-05](https://user-images.githubusercontent.com/49316253/57198165-ef65f400-6f6f-11e9-8211-85735bdd8166.gif)
im on the verge of giving up.

**Comment by yeahoffline** [comment]
as I said, its a CORS issue. check your developer tools (network tab).

if you use chrome you can use a plugin that disables CORS.

on the other hand you can check out the source code and mock the backend :)
