### ISSUE TITLE
login fires 2 api calls 

### ISSUE THREAD

**Issue by yeahoffline** [blockkeeper/blockkeeper-frontend-web#8]
Summary: user login fires a second login call

Steps to reproduce: logout, login to any user, find 2 /login/{username} calls

Expected results: user login should fire only a single login call to get all the necessary data

Actual results: duplicate /login/{username} call

**Comment by d3ck-org** [comment]
FYI: https://github.com/blockkeeper/blockkeeper-backend/issues/9.
